# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

executors:
  golang:
    environment:
      GO111MODULE: "on"
      VERSION: 2018.06.24
    docker:
      - image: golang:1.12
    working_directory: /go/src/github.com/j4ng5y/rng-deity

jobs:
  flow:
    executor: golang
    steps:
      - checkout
      - run: go mod download
      - run: go test -v ./...
      - run: go build -o /go/bin/rng-deity-${CIRCLE_BRANCH}-linux-amd64
      - persist_to_workspace:
          root: /go
          paths:
            - bin
  downstream:
    executor: golang
    steps:
      - attach_workspace:
          at: /go/bin
      - run: go get github.com/tcnksm/ghr
      - run: ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete $VERSION /go/bin/

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - flow:
          filters:
            branches:
              only: /releases/.*/
      - downstream:
          requires:
            - flow